### ISSUE TITLE
Getting NoSuchMethodError when executing stjs task

### ISSUE THREAD

**Issue by johnhall** [dzwicker/st-js-gradle-plugin#8]
I can't find a way around this error.  It looks like there is a dependency issue when executing the plugin task, but I'm not sure.  Here's the abbreviated stacktrace:
- Exception is:
  org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':stjs'.
  : **abbreviated here to cut down on the noise**
  Caused by: java.lang.NoSuchMethodError: com.google.common.io.Files.copy(Lcom/google/common/io/InputSupplier;Ljava/io/File;)V
  at org.stjs.generator.Generator.copyJavascriptSupport(Generator.java:251)
  at com.github.dzwicker.stjs.gradle.GenerateStJsTask.filesGenerated(GenerateStJsTask.java:228)
  at com.github.dzwicker.stjs.gradle.GenerateStJsTask.generate(GenerateStJsTask.java:217)
  at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
  at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:227)
  at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
  at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
  at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
  at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
  ... 70 more

**Comment by johnhall** [comment]
Sorry; didn't add more useful info.  I'm using the 3.2.2 version of your plugin:
        classpath("com.github.dzwicker.stjs.gradle:st-js-gradle-plugin:3.2.2")
and:
            'org.st-js:stjs:3.3.0',
            'org.st-js.bridge:jquery:1.11.3.bv1',
The Javascript file is created from the target domain model class, but then the failure occurs.

**Comment by dzwicker** [comment]
You are write. This is a dependency issue with the google guava lib. The plugin uses guava-17.0. And the plugin is compiled against the 3.2.2 versions of stjs libs. I'm not sure if this can cause this problem.

Can you check if there is another version of the guava jar configurated in you project? If so try to pin the guava version to 17.0 for your buildscript deps.

**Comment by dzwicker** [comment]
Will try to update the plugin to uses the 3.3.0 or what ever the newest version of stjs is in the next days....
